# Generated by Django 5.0.3 on 2024-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(blank=True, max_length=100, null=True, verbose_name='palavra')),
                ('definicao', models.CharField(blank=True, max_length=500, null=True, verbose_name='definicao')),
                ('origem', models.CharField(blank=True, max_length=500, null=True, verbose_name='origem')),
            ],
        ),
    ]
