# Generated by Django 5.0.3 on 2024-03-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docionario',
            new_name='Dicionario',
        ),
    ]
