# Generated by Django 5.0.3 on 2024-03-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_rename_docionario_dicionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome: ')),
                ('height', models.IntegerField(verbose_name='altura: ')),
                ('weight', models.IntegerField(verbose_name='peso: ')),
                ('tipo_pokemon', models.CharField(max_length=30, verbose_name='tipo do pokemon: ')),
            ],
        ),
        migrations.DeleteModel(
            name='Dicionario',
        ),
    ]
